O auth
ZakirovRifkat/Scheduler pull request #10
Opened 2023-05-24 18:11 UTC by KashevarovStepan

2023-05-24 21:14 UTC, ialexi-bl requested changes
В целом ок, респект. Ща напишу ниже что нужно поправить кроме мелочей которые накидал, как минимум чтобы нормально запомнить пользователя, а не создавать нового на каждый чих

2023-05-24 21:14 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/SecurityConfig.java
> +/*package com.mazyavr.schedule;
Если не нужен этот файл, удалить

2023-05-24 21:14 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +    return userCalendar;
Можно чуть проще написать

```suggestion
    try {
      var HTTP_TRANSPORT = GoogleNetHttpTransport.newTrustedTransport();
      var credential = new GoogleCredential().setAccessToken(userToken);

      return new Calendar.Builder(HTTP_TRANSPORT, JSON_FACTORY, credential)
          .setApplicationName("DownScheduler")
          .build();
    } catch (IOException | GeneralSecurityException e) {
      throw new RuntimeException("Unable to initialize google calendar");
    }
```

2023-05-24 21:14 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +   * Здесь реализована только регистрация(добавление в БД), но не авторизация(обновление юзверя в
Авторизация вообще это не обновление юзера в БД, но пофиг на комменты

2023-05-24 21:14 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +      cookie.setMaxAge(86400);
Один день маловато, можно было бы хотя бы недельку, но не принципиально

2023-05-24 21:14 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/entity/UserEntity.java
> +  private long email;
Имейл это `long`?

2023-05-24 21:14 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/service/ProjectService.java
> +    UserEntity user = user0.get();
Надо определиться, как опшионалы обозначаются, либо заглавная о на конце, либо ноль. У нас до этого обозначались с о, так что предлагается продолжать эту практику, но это так лирическое отступление, не слишком важно

```suggestion
    var userO = userRepository.findById(userId);

    if (userO.isEmpty()) {
      throw new IllegalArgumentException("No such user");
    }

    UserEntity user = userO.get();
```

2023-05-24 21:26 UTC, ialexi-bl commented
В общем, история следующая, я фигею с того насколько отвратительный API у гугла и насколько нереально в принципе найти информацию о том, как что либо блин сделать по-человечески, но я таки нашёл грёбанный способ достать имейл пользователя и айдишник. Это делается так: после того как мы получили code от гугла и сделали вот эту шляпу с `GoogleAuthorizationCodeTokenRequest`, мы кроме `accessToken` и `refreshToken` получаемся ещё некоторого кота в мешке с названием `idToken`. Из него можно вытащить имейл и айди пользователя в гугле, делается так:

```java
var HTTP_TRANSPORT = GoogleNetHttpTransport.newTrustedTransport();
var JSON_FACTORY = GsonFactory.getDefaultInstance()
var CLIENT_ID = "5308..."
GoogleTokenResponse response = new GoogleAuthorizationCodeTokenRequest(
  HTTP_TRANSPORT, JSON_FACTORY, CLIENT_ID, .......
).execute();

var idToken = response.getIdToken();
var verifier = new GoogleIdTokenVerifier.Builder(HTTP_TRANSPORT, JSON_FACTORY)
                .setAudience(Collections.singletonList(CLIENT_ID)
                .build()
var verifiedToken = verifier.verify(idToken);
if (verifiedToken != null) {
  var payload = verifiedToken.getPayload();
  var googleId = payload.getSubject();
  var email = payload.getEmail();
}
```

Собственно вот, `googleId` и `email` это некоторые идентификаторы, которые мы можем себе записывать и использовать, чтобы запомнить пользователя. Поэтому надо сделать следующее:

1. В таблице пользователей думаю email нам не нужен, вместо него сделать колонку `googleId` в которую будем сохранять айди гугла тот самый. Колонку `token` лучше переименовать в `refreshToken`, чтобы не путаться какой из 15 видов токенов именно там хранится
2. При регистрации написать вот эту залупу которая наверху. После этого проверить, есть ли в БД уже пользователь с `googleId` равным тому вот который мы из токена вытащили. Если уже есть, перейти к шагу 4, если нет к шагу 3
3. Создать пользователя со случайным `id`; `googleId` взять из токена, в колонку `refreshToken` записать собственно рефреш токен который можно получить в коде выше, вызвав `response.getRefreshToken()`
4. В куку записать айди пользователя, типа он залогинился
5. Профит
6. Далее только чуть-чуть поправить надо будет в ручках интеграции с гуглом. Функция `initCalendar` так как в ней не будет больше напрямую доступа к `accessToken`, а будет только `user.getRefreshToken()`, надо обменять `refreshToken` на `accessToken`. Это очень просто:

    ```java
var response = new GoogleRefreshTokenRequest(
  HTTP_TRANSPORT, JSON_FACTORY, refreshToken, "client_id", "client_secret"
);
var accessToken = response.getAccessToken();
```

   И уже этот `accessToken` передаём в конструктор `GoogleCredential`

2023-05-24 21:32 UTC, KashevarovStepan commented on src/main/java/com/mazyavr/schedule/entity/UserEntity.java
> +  private long email;
нет, это позор, должна быть строка

2023-05-24 21:33 UTC, KashevarovStepan commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +      cookie.setMaxAge(86400);
ну нам главное показать, так что не суть, я думаю

2023-05-24 21:36 UTC, ialexi-bl commented
Это по поводу сохранения привязки пользователя к аккаунту. Далее насчёт авторизации пару слов. Требовать передавать в ручки `userId` чтобы уточнить, задачи какого пользователя надо получать, в целом рабочий вариант. Единственное если делать прям по техникам REST, то желательно их передавать не в квере (после знака вопроса), а как часть пути. Типа если тебе нужно получить "задачу 1 в проекте 4 пользователя 78", то ты будешь делать запрос на путь `/users/78/projects/4/tasks/1`. Чтобы так сделать, надо в пути ручки указать, что часть пути является подстановкой, типа `/users/:userId/projects/:projectId/tasks/:taskId`, и дальше в переменных метода-обработчика получать их значения с помощью аннотации `@PathVariable`, а не `@RequestParam`. Но это если совсем упарываться в лучшие практики REST, в целом нам насрать по большей части, учитывая что бóльшая часть ручек у нас и так не следует REST. Более содержательно (но тоже сейчас за неимением времени не обязательно для выполнения) следующее.

Авторизация. Если всё-таки бы мы хотели запретить другим пользователям просматривать и тем более редактировать чужие задачи, то на каждый запрос потенциально опасный нужно было бы проверять, что пользователь авторизован, и что имеет право менять задачи. Для этого можно было бы создать какой-нибудь метод типа `long getCurrentUser()`, который бы считывал куку `userId` и возвращал его значение. И потом ты бы проверял, имеет ли право пользователь что-то делать, например так

```
@GetMapping("/projects/all")
public @ResponseBody ProjectsListDto getProjects(@RequestParam long userId) {
  long currentUserId = getCurrentUser();
  if (userId != currentUserId) {
    throw new ResponseStatusException(HttpStatus.FORBIDDEN, "You can only see your tasks");
  }

  // ...

}
```

Это просто на заметку, нам реализовывать сейчас не обязательно

2023-05-25 12:34 UTC, ialexi-bl requested changes

2023-05-25 12:34 UTC, ialexi-bl commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
>        var credential = new GoogleCredential().setAccessToken(userToken);
Это не будет работать, метод `setAccessToken`, а в него передаётся `refreshToken`, так не получится. Писал в комменте там, как можно обменять `refreshToken` на `accessToken`, нужно это сделать здесь сначала, а потом создавать `GoogleCredential`

2023-05-25 12:34 UTC, ialexi-bl commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +      this.refreshToken = response.getAccessToken();
Это поле больше не нужно, мы токен берём из БД а не из поля. Надо удалить поле `this.refreshToken`

2023-05-25 12:34 UTC, ialexi-bl commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +      }
Если `verifiedToken == null`, то мы н можем проверить зарегистрирован ли пользователь. Можно кидать исключение, если проверка не прошла. И ещё, переменная `googleId` должна быть локальная, а не поле класса, её значение вне этого метода не должно быть доступно

```suggestion
      if (verifiedToken == null) {
        throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "No user ID provided");
      }
      
      var googleId = verifiedToken.getPayload().getSubject();
```

2023-05-25 12:34 UTC, ialexi-bl commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
>        this.lifespan = Math.toIntExact(response.getExpiresInSeconds());
`lifespan` по-моему тоже не нужно поле, надо его удалить

2023-05-25 12:34 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +        } while (!isFree);
Это вроде как не нужно, айди в mysql будет генерироваться автоматически. Просто не заполняй его в `user`

```suggestion
```

2023-05-25 12:34 UTC, jabuj commented on src/main/java/com/mazyavr/schedule/controller/UserController.java
> +      if (user != null){
Наверное всё-таки

```suggestion
      if (user == null) {
```

2023-05-25 12:34 UTC, ialexi-bl commented on src/main/java/com/mazyavr/schedule/dto/UserDto.java
> +public record UserDto(long id, String email, String token) {
В `UserEntity` поля переименовали на `googleID` и `refreshToken`, здесь тоже надо

2023-05-25 12:34 UTC, ialexi-bl commented on src/main/java/com/mazyavr/schedule/service/TaskService.java
> +      if (t.getId()==userId&&t.getStart().compareTo(time.plusDays(1)) < 0 && t.getEnd().compareTo(time) >= 0 && !t.isStatus()) {
Зачем это изменение? Надо сравнивать айди пользователя, а `t.getId()` это айди таски а не пользователя.

```suggestion
      if (t.getProject().getUser().getId() == userId && t.getStart().compareTo(time.plusDays(1)) < 0 && t.getEnd().compareTo(time) >= 0 && !t.isStatus()) {
```

2023-05-31 19:47 UTC, ialexi-bl commented
Влили изменения в #11

2023-05-31 19:47 UTC, closed without merging